export enum HardwareTypes {
  MASCHINE_MK3 = 'MASCHINE MK3',
  MASCHINE_MIKRO_MK3 = 'MASCHINE MIKRO MK3'
}

export enum ModeTypes {
  CLIP = 'CLIP',
  SCENE = 'SCENE',
  TRACK = 'TRACK'
}

export enum ActionType {
  TOGGLE,
  TOGGLE_SMALL,
  TOUCH_STRIP,
  JOG_WHEEL_ROTATE,
  JOG_WHEEL_PUSH,
  PAD,
  SEPARATOR_SLASH,
  SEPARATOR_PLUS,
  PLAY,
  REC,
  STOP,
  SHIFT,
  MASCHINE,
  FAVOURITE,
  BROWSER
}
